### ISSUE TITLE
Works good, but too simple

### ISSUE THREAD

**Issue by Kitzoon** [MoleTheDev/DankMemer-Farmer#14]
you dont really earn much from this but it still works good none the less

some suggestions:
- more farm tasks to do (I find the ones that pay a lot are more skill based, but that might be an issue since a self bot probably cant do those)
- visual upgrades, like making the terminal title have stats for how many times you've done a task
- stop command

**Comment by MoleTheDev** [comment]
Yea i kinda rushed to update the bot to use node.js instead of Python, but yes i will implement those, Thanks!
