### ISSUE TITLE
ERROR. pls help

### ISSUE THREAD

**Issue by suryansh00123** [MoleTheDev/DankMemer-Farmer#15]
I performed all the pre-requisites, but When Run command node src/index.js inside the DankMemer-Farmer folder in CMD
the following error shows up. refer(image)
![error](https://user-images.githubusercontent.com/62205232/193450321-1bed50ec-8258-4480-bf4f-76b1697878ec.png)

**Comment by MoleTheDev** [comment]
can you show me the files in the current directory?
run ```dir``` or ```ls``` to get the files in the current directory

**Comment by MoleTheDev** [comment]
1 week no reply
