### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by FilthyNoempt** [MoleTheDev/DankMemer-Farmer#16]
can u make one for replit/heroku with variable so i can host there and can u make it like i can use multiple tokens at the same time pwease

**Comment by MoleTheDev** [comment]
I'm working on a new version that will also support reading from the environment variables instead of using the configuration file.

meanwhile you can use [Railway](https://railway.app/) for hosting the bot.

**Comment by MoleTheDev** [comment]
Added.
