### ISSUE TITLE
Buttons! (read the write please)

### ISSUE THREAD

**Issue by UnPurgable** [MoleTheDev/DankMemer-Farmer#2]
Ik your previous answer said not for now but this may come and be useful!
https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/examples/buttons.py

**Comment by MoleTheDev** [comment]
> Ik your previous answer said not for now but this may come and be useful! https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/examples/buttons.py

Nice! this is pretty interesting i guess i will give it a try

Thanks!
