### ISSUE TITLE
Method

### ISSUE THREAD

**Issue by Yoon0117** [MoleTheDev/DankMemer-Farmer#4]
I can't use
`git clone https://github.com/MoleTheDev/DankMemer-Farmer/edit/main/bot.py`
![image](https://user-images.githubusercontent.com/90393596/172040092-70e9068f-ff68-403a-9e5a-a26c3cdab5f0.png)

**Comment by MoleTheDev** [comment]
Hello,
You are using the specific link to ```bot.py``` file, and this doesn't work, you need to clone the whole repository,

do this:
```
git clone https://github.com/MoleTheDev/DankMemer-Farmer
```
