### ISSUE TITLE
so i got to the end and it says "missing something something argument "intents""

### ISSUE THREAD

**Issue by holy-milk-lord** [MoleTheDev/DankMemer-Farmer#6]
i did everything and did colorama and discord things put my token it with "" and yea

**Comment by holy-milk-lord** [comment]
also im goin to bed

**Comment by holy-milk-lord** [comment]
![Screenshot (92)](https://user-images.githubusercontent.com/112532518/187585242-76689930-76f3-4be2-825a-1b33c5f11e2f.png)

**Comment by holy-milk-lord** [comment]
![Screenshot (93)](https://user-images.githubusercontent.com/112532518/187585362-4fc1c48c-0482-4110-97c5-04bb183d4089.png)

**Comment by holy-milk-lord** [comment]
also sence the new update i changed these idk if itll work but i had to change it :/
![Screenshot (95)](https://user-images.githubusercontent.com/112532518/187586677-21180340-e3f6-4880-8c06-09b3da87aa62.png)

**Comment by MoleTheDev** [comment]
Hi.
Discord uses another API for slash commands messages handling, you (we) can't simply just use ```ctx.send("/blah")```
And there's no function in Discord.py that allows a self-bot that against the ToS to use such another bot slash command.

I'm trying to find a way using their API right now

**Comment by MoleTheDev** [comment]
I updated the [READM](https://github.com/MoleTheDev/DankMemer-Farmer) to prevent more related issues to this one.

I will keep this issue open too.

**Comment by holy-milk-lord** [comment]
sending the / command would be selecting that specific command then the " " would be sending that slash

**Comment by holy-milk-lord** [comment]
also thx

**Comment by MoleTheDev** [comment]
> sending the / command would be selecting that specific command then the " " would be sending that slash

No it doesn't work like that
that would raise an error for empty message

**Comment by MoleTheDev** [comment]
Updated

Closing this issue.
