### ISSUE TITLE
how do i fix 

### ISSUE THREAD

**Issue by asdfawjbhsdhbasjindh** [MoleTheDev/DankMemer-Farmer#8]
Traceback (most recent call last):
  File "C:\Dank Memer Autofarm\bot.py", line 2, in <module>
    from slashCommands import *
  File "C:\Dank Memer Autofarm\slashCommands.py", line 3, in <module>
    ws = websocket.WebSocket()
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'
 

This is the error that it gave me.

**Comment by MoleTheDev** [comment]
You have installed the mistaken ```websocket``` library You need to use/install ```websocket-client``` instead of ```websocket```.

First, uninstall ```websocket```:
```
pip uninstall websocket
```
and then install ```websocket-client```:
```
pip install websocket-client
```

Inform me with a comment here if it got solved after installing the correct library.
