### ISSUE TITLE
new error about missing something intents

### ISSUE THREAD

**Issue by asdfawjbhsdhbasjindh** [MoleTheDev/DankMemer-Farmer#9]
sorry if im just dumb or something but when I run the program I get this error immediately.

Traceback (most recent call last):
  File "C:\Dank Memer Autofarm\bot.py", line 7, in <module>
    client = commands.Bot(command_prefix=prefix, self_bot=True)
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by MoleTheDev** [comment]
what version of discord.py have you installed?
*Hint:*

run ```pip freeze``` and in the output you can find the version of discord.py

**Comment by asdfawjbhsdhbasjindh** [comment]
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==22.1.0
certifi==2022.6.15.1
cffi==1.15.1
charset-normalizer==2.1.1
colorama==0.4.5
discord.py==2.0.1
frozenlist==1.3.1
gevent==21.12.0
greenlet==1.1.3
idna==3.3
init==0.1.0
multidict==6.0.2
pycparser==2.21
pynput==1.7.6
PyYAML==6.0
requests==2.28.1
six==1.16.0
terminal==0.4.0
urllib3==1.26.12
websocket-client==1.4.1
yarl==1.8.1
zope.event==4.5.0
zope.interface==5.4.0

**Comment by asdfawjbhsdhbasjindh** [comment]
discord.py==2.0.1

**Comment by MoleTheDev** [comment]
> discord.py==2.0.1

In this latest version, the "intents" parameter should be passed inside the client variable (```commands.Bot()```) in order to run the bot and ```bot=False``` parameter seems to be removed & changed in this version?

The only way is to downgrade to version 1.7.3:
```bash
pip install discord.py==1.7.3
```

**Comment by asdfawjbhsdhbasjindh** [comment]
tysm it works now

**Comment by asdfawjbhsdhbasjindh** [comment]
![image](https://user-images.githubusercontent.com/88472260/190647622-6dc72c02-e7aa-4371-8c26-53413538622c.png)
although it says it is logged in its not sending the messages in the channel

**Comment by MoleTheDev** [comment]
You need to send ```?farm``` in the discord channel you specified, not in the terminal.

run with ```True``` parameter to enable auto-deposit -> ```?farm True```

**Comment by asdfawjbhsdhbasjindh** [comment]
thanks so much it works now

**Comment by MoleTheDev** [comment]
No Problem!

**Comment by MoleTheDev** [comment]
👍🏻
